apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandeep-dep
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sandeep-dep
  template:
    metadata:
      labels:
        app: sandeep-dep
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: sandeep-pod
        ports:
        - containerPort: 80
